### ISSUE TITLE
possible interference with axios requests.

### ISSUE THREAD

**Issue by OneMoreRound82** [alexsabdev/vue-drift#2]
I may have an issue where the Drift plugin is constantly calling bulk, or bulk_enroll and this is interrupting a request to my server - although im not 100% this is the cause.

Is there a way to just have this Drift plugin on certain pages, without just hiding it?  If I hide it, it still makes the bulk / bulk_enroll calls.

So instead of putting these lines in my main.js:

import VueDrift from 'vue-drift'
Vue.use(VueDrift, {
  appId: 'xxxxxxxxxxx',
})

I could include them as part of a Vue component?  And that way just have it appearing on my main page?

**Comment by alexsabdev** [comment]
`Bulk` and `bulk_enroll`'s must be async monitoring calls sent by Drift itself. Not sure if they could interrupt your requests...

Unfortunately, the plugin should be set up globally for an SPA. If it was installed locally, you'd do some voodoo on router change... As a workaround, you can play with targeting options [here](https://app.drift.com/settings/widget/hours-and-targeting) (if you are on a paid plan).

Let me know if you have any questions.

**Comment by OneMoreRound82** [comment]
Thanks for coming back to me Alex, I think my problem maybe elsewhere but
thank you for your response. It's a great plugin, well done on it!
