### ISSUE TITLE
.hide() and .show() not working

### ISSUE THREAD

**Issue by juandanceswild** [alexsabdev/vue-drift#9]
Hi, 

I have set up the integration for drift on my app. I only need the widget in certain components of the app, so I set it up like suggested on the app. 

In App.vue:
- I watch route and call this.$drift.page() on route change.
- In mounted() I call this.$drift.hide()

In the component where I need the widget
- In mounted() I call this.$drift.show()

However, the widget is appearing throughout the app. It's as if the hide and show calls aren't working.

**Comment by alexsabdev** [comment]
@juandanceswild it must because the `mounted` hook of `App.vue` is usually called just once, so the app doesn't hide the widget again as you leave the component. Try adding `this.$drift.hide()` to the `destroyed` hook of your component. If it doesn't help, please create a minimal reproducible repo so I can take a look.

Ps: the `page` method has nothing to do with visibility. Please check [this](https://devdocs.drift.com/docs/contact-properties#driftpage) for details.

**Comment by juandanceswild** [comment]
@alexsabdev thank you for your response.

In this case, App.vue is the parent component of all components (it contains <router-view>), so it doesn't get destroyed until the user closes the window. 

However, I did what you suggested and the issue persists.

I will make a sandbox example of this when I get a chance.

**Comment by alexsabdev** [comment]
@juandanceswild I mean you need to add `this.$drift.hide()` to the `destroyed` hook of the CHILD component (where you need the widget shown)

**Comment by juandanceswild** [comment]
What's weird is that the widget appears even before I navigate to the route of the component where `.show()` is called.

I `.hide()` it on App.vue, and go directly to the `'/'` route of the app where there is no `.show()`, and yet it is there...

**Comment by alexsabdev** [comment]
@juandanceswild looks like I got confused a little bit. Once again, it's what I suggest:

In App.vue:
`mounted() {
  this.$drift.hide()
}`

In ChildComponent.vue:
`
mounted() {
  this.$drift.show()
},
destroyed() {
  this.$drift.hide()
}
`

**Comment by FounderCasey** [comment]
Just a note - this solution is working for me currently.

> In App.vue:
> mounted() { this.$drift.hide() }
> 
> In ChildComponent.vue:
> mounted() { this.$drift.show() }, destroyed() { this.$drift.hide() }

**Comment by alexsabdev** [comment]
thanks for your feedback @FounderCasey
